### PR TITLE
Add mqttc.last_will for availability_topic

### PR DESCRIPTION
**Pull request by TimWeyand**
+ Add last_will before connection (comfoair/status => offline)
+ Add message after connection (comfoair/status => offline)
+ Update Configuration example
- Remove own Debian modifications
- Remove servicetest

### CODE REVIEW

**Review by adorobis — APPROVED** [review]

**Comment by adorobis** [comment]
Many thanks for contributions!

**Comment by adorobis** [comment]
Regarding the PC mode I've never managed to make it work - in theory it should allow to keep the comfo control panel to be connected at the same time - I needed to disconnect it to allow the PC to control the unit.

**Comment by adorobis** [comment]
@TimWeyand 
And one question - how did you integrate it with HA? Have you created a separate sensor for the availability topic or it somehow integrates out of the box?

**Comment by TimWeyand** [comment]
Hi @adorobis,
i use pc mode to disable the comfoair comfosense, thats the main reason i use it. As soon as i start the service, i want it to take control. If the service stops, then i would like to enable comfoair itself.

I am used to it on openhab 1 (right now i am switching to HA), i had an toogle in openhab 1 but i wouldn't expose it to mqtt - it should be more an service setting.

The next things i am looking for and hope that i can help with, is:
+ Make your service work with https://github.com/wichers/lovelace-comfoair 
+ Add mqtt autodiscovery (seems to only work with havc not fans)
+ Move Configurations to the top (username, password, pcmode enable, ha mqtt topic).

I am not used to program in python or HA so much, so lets see what i can do 🙂

**Pull request merged**
